repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: debug-statements  # Prevents accidental debug prints

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black  # Auto-formats Python code

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.2
    hooks:
      - id: flake8  # Lints Python code
        args: ["--ignore=W503,F401,B101"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff  # Faster alternative to Flake8 with autofixes
        args: ["--ignore=F401"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit  # Security analysis for Python
        args: ["--skip", "B101,B201,B311"]
