version: "3.8"

services:
  async_api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    env_file:
      - ./.env

  redis:
    image: redis:6.2
    container_name: ${REDIS_HOST}
    command: [ "redis-server", "--port", "${REDIS_PORT}" ]
    expose:
      - "${REDIS_PORT}"
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "${REDIS_PORT}", "--raw", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: ${ELASTIC_HOST}
    environment:
      - ES_LOG_LEVEL=ERROR
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - http.port=${ELASTIC_PORT}
    expose:
      - "${ELASTIC_PORT}"
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "curl -s ${ELASTIC_SCHEME}://${ELASTIC_HOST}:${ELASTIC_PORT} >/dev/null || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 120s
      timeout: 10s
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  es_data: