services:
  async_api:
    build: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    env_file:
      - ./.env

  redis:
    image: redis:6.2
    expose:
      - "6379"
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    expose:
      - "9200"
    ports:
      - "9200:9200"
    env_file:
      - ./.env
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
