services:
  redis:
    ports:
      - "6379:6379"

  elasticsearch:
    ports:
      - "9200:9200"

  postgres:
    ports:
      - "5432:5432"

  jaeger:
    ports:
      - "5775:5775/udp"  # для zookeeper
      - "6831:6831/udp"  # для agent
      - "6832:6832/udp"  # для agent
      - "5778:5778"      # для HTTP API
      - "14250:14250"    # для gRPC
      - "14268:14268"    # для HTTP API (спаны)
      - "16686:16686"    # для UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
