version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - ELASTIC_HOST=${ELASTIC_HOST}
      - ELASTIC_PORT=${ELASTIC_PORT}
    depends_on:
      - redis
      - elastic
    volumes:
      - .:/app

  redis:
    image: "redis:6.2"
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.10"
    container_name: elastic
    environment:
      - discovery.type=single-node
    ports:
      - "${ELASTIC_PORT}:${ELASTIC_PORT}"
      - "9300:9300"