"""add email to users

Revision ID: 0d980fadd1c8
Revises: e65fc0a3d37a
Create Date: 2025-04-12 20:55:27.270317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d980fadd1c8'
down_revision: Union[str, None] = '09592f65e6a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = '09592f65e6a3'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'login_history', ['id', 'user_device_type'], schema='auth')
    op.add_column('users', sa.Column('email', sa.String(), nullable=True), schema='auth')
    op.create_unique_constraint(None, 'users', ['email', 'partition_country'], schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique', schema='auth')
    op.drop_column('users', 'email', schema='auth')
    op.drop_constraint(None, 'login_history', type_='unique', schema='auth')
    # ### end Alembic commands ###
