"""add oauth_id to users

Revision ID: 1772518850c1
Revises: 0d980fadd1c8
Create Date: 2025-04-12 21:18:11.790594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1772518850c1'
down_revision: Union[str, None] = '0d980fadd1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['oauth_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'oauth_id')
    # ### end Alembic commands ###
