name: Main movies workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  continuous_integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.10, 3.11, 3.12 ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install \
            wemake-python-styleguide==0.21.0 \
            flake8-html==0.3.0 \
            mypy==1.5.0

      - name: Run wemake-python-styleguide (HTML report)
        run: flake8 . --format=html --htmldir=reports/flake8

      - name: Upload lint report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: flake8-report
          path: reports/flake8/

      - name: Run mypy type checks
        run: mypy .

      - name: Upload mypy report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mypy-report
          path: reports/mypy.log

  send_message:
    runs-on: ubuntu-latest
    needs: continuous_integration
    if: always()

    steps:
      - name: Determine target URL
        id: target_url
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "url=https://github.com/${{ github.repository }}"
            echo -n "/commit/${{ github.sha }}"
          else
            echo "url=https://github.com/${{ github.repository }}"
            echo -n "/pull/${{ github.event.pull_request.number }}"
          fi > url.txt
          echo "::set-output name=url::$(cat url.txt)"

      - name: Notify Telegram on success
        if: needs.continuous_integration.result == 'success'
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to:    ${{ secrets.TELEGRAM_TO }}
          message: |
            ✅ Тесты успешно выполнены.
            • Репозиторий: ${{ github.repository }}
            • Событие: ${{ github.event_name }}
            • Автор: ${{ github.actor }}
            • Сообщение коммита: ${{ github.event.commits[0].message }}

            • Ссылка:  ${{ steps.target_url.outputs.url }}

      - name: Notify Telegram on failure
        if: needs.continuous_integration.result != 'success'
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to:    ${{ secrets.TELEGRAM_TO }}
          message: |
            ❌ Тесты не пройдены.
            • Репозиторий: ${{ github.repository }}
            • Событие: ${{ github.event_name }}
            • Автор: ${{ github.actor }}
            • Сообщение коммита: ${{ github.event.commits[0].message }}

            • Ссылка:  ${{ steps.target_url.outputs.url }}